### ISSUE TITLE
Line 160 I$ should be i$ for vice

### ISSUE THREAD

**Issue by LBXComputers** [HAnthonyHoyt/c64-dungeon-of-doom#1]
For copy and pasting this code in to VICE, the I$ on line 160 should be i$

**Comment by HAnthonyHoyt** [comment]
Sorry this is so late to correct!  I'll get on this. @LBXComputers

**Comment by HAnthonyHoyt** [comment]
I can't believe how long it took for me to remember this.  Fixed and pushed.
