### ISSUE TITLE
Missing, extra or different characters

### ISSUE THREAD

**Issue by LBXComputers** [HAnthonyHoyt/c64-dungeon-of-doom#2]
I'm trying to make my code as authentic as possible and found your interpretation of the original source but noticed some things different to my version.

The original book's code has a semi-colon on the end of lines 50, 340.

There should also be a full stop/period on the "one moment please" section on line 450

The original book's code did not have a semi-colon on the end of line 580

Also where you have "co" variable in your code, the original book was "c0".

**Comment by HAnthonyHoyt** [comment]
Thank you, I'll look over this and try to get it all corrected.  Sadly, I don't have an authentic C64 to test this on, so I can't easily test this code, specially lacking a datasette.

**Comment by LBXComputers** [comment]
> Thank you, I'll look over this and try to get it all corrected. Sadly, I don't have an authentic C64 to test this on, so I can't easily test this code, specially lacking a datasette.

Nor me, I did it all in VICE.

**Comment by HAnthonyHoyt** [comment]
All changes should now be resolved. Thanks for the heads up.
